"use client";

import { useFormState, useFormStatus } from "react-dom";
import { useEffect } from "react";
import { summarizeSermonAction } from "@/app/actions/sermon-actions";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Loader2, Terminal } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

function SubmitButton() {
  const { pending } = useFormStatus();
  return (
    <Button type="submit" disabled={pending} className="w-full">
      {pending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
      Generate Summary
    </Button>
  );
}

export function SermonSummarizer() {
  const { toast } = useToast();
  const [state, formAction] = useFormState(summarizeSermonAction, {
    message: "",
  });

  useEffect(() => {
    if (state.message && state.errors) {
      toast({
        variant: "destructive",
        title: "Error",
        description: state.message,
      });
    }
  }, [state, toast]);

  return (
    <div className="max-w-2xl mx-auto mt-20">
      <h3 className="text-3xl font-headline italic text-center text-white mb-4">
        AI Sermon Summarizer
      </h3>
      <p className="text-purple-100 text-center mb-8 font-light">
        Paste a sermon transcript below to get a concise summary generated by AI.
      </p>
      <Card className="bg-white/5 border-white/10 text-white">
        <CardContent className="pt-6">
          <form action={formAction} className="space-y-4">
            <Textarea
              name="sermonText"
              placeholder="Paste sermon text here... (minimum 100 characters)"
              className="bg-black/20 border-white/20 min-h-[200px] text-base"
              required
            />
            {state?.errors?.sermonText && (
              <p className="text-sm text-red-400">{state.errors.sermonText[0]}</p>
            )}
            <SubmitButton />
          </form>
        </CardContent>
      </Card>

      {state.summary && (
        <Card className="mt-8 bg-white/5 border-white/10 text-white">
          <CardHeader>
            <CardTitle>Generated Summary</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-purple-100 whitespace-pre-wrap">{state.summary}</p>
          </CardContent>
        </Card>
      )}

      {state.message && !state.summary && state.errors && (
         <Alert variant="destructive" className="mt-4">
           <Terminal className="h-4 w-4" />
           <AlertTitle>Summarization Failed</AlertTitle>
           <AlertDescription>
             {state.message} Please check the sermon text and try again.
           </AlertDescription>
         </Alert>
      )}
    </div>
  );
}
